import { pricing } from '@/lib/pricing-data';

// ---- SERVIZI -------------------------------------------------------
// Ogni servizio ha una pagina dedicata (/servizi/<slug>). caseStudySlug e
// testimonialName riusano i case study e le testimonianze concept già
// dichiarati in portfolio: nessun nuovo cliente o numero inventato.
export const servizi = [
  {
    slug: 'ecommerce-shopify',
    n: '02',
    tag: 'SHOPIFY',
    icon: 'cart',
    title: 'E-commerce Shopify performanti',
    seoTitle: 'E-commerce Shopify per Vendite Dirette',
    seoDescription:
      'E-commerce Shopify veloci che convertono: pagamenti sicuri, spedizioni automatizzate, gestione inventario. Aumenta le vendite dirette online.',
    heroImage: '/images/servizi/ecommerce-shopify-hero.jpg',
    body: 'Store costruiti per vendere: schede prodotto, checkout e percorso d’acquisto ottimizzati. Focus su velocità, chiarezza e conversione, non solo estetica.',
    resultNote: 'Un canale di vendita diretta che riduce la dipendenza da grossisti e distributori.',
    tesi: 'Vendere direttamente vale più che vendere di più.',
    problemBlock: {
      eyebrow: 'Ci risulta che vada più o meno così',
      paragraphs: [
        'Vendete già. Il punto è a chi resta il margine.',
        'Se vendete tramite intermediari o piattaforme, su ogni bottiglia c’è qualcuno che prende una parte. E soprattutto: il cliente è loro, non vostro. Non sapete chi è, non potete riscrivergli, non torna da voi ma da loro.',
        'Vendere diretto non è vendere di più. È tenere il margine e tenere il cliente.',
      ],
      image: '/images/servizi/ecommerce-shopify-problema.webp',
      imageAlt: 'Scatole di spedizione pronte per la distribuzione all’ingrosso',
    },
    changeBlock: {
      heading: 'Cosa cambia con uno store costruito per il vostro settore',
      paragraphs: [
        'Chi vi trova online compra direttamente da voi: niente commissioni a un intermediario, e il contatto resta vostro per il riacquisto.',
        'Il catalogo racconta il prodotto — annata, varietà, provenienza — invece di trattarlo come una merce qualsiasi, e propone formati e bundle nel momento giusto, non come ripensamento a fine carrello.',
        'Chi abbandona il carrello riceve un promemoria automatico, e chi ha già comprato resta un contatto a cui potete riscrivere per la stagione successiva.',
      ],
      image: '/images/servizi/ecommerce-shopify-cambia.webp',
      imageAlt: 'Bottiglia confezionata con cura per la spedizione diretta al cliente',
    },
    includes: [
      { icon: 'cart', title: 'Catalogo e schede che raccontano', body: 'Non solo prezzo: varietà, provenienza, metodo di produzione.' },
      { icon: 'gift', title: 'Formati e bundle', body: 'Confezioni regalo, assortimenti, abbonamenti ricorrenti.' },
      { icon: 'compass', title: 'Spedizione Italia ed estero', body: 'Zone, corrieri e costi impostati per il vostro prodotto.' },
      { icon: 'lock', title: 'Pagamenti', body: 'Shopify Payments, carte, PayPal, Klarna dove serve.' },
      { icon: 'refresh', title: 'Recupero carrelli abbandonati', body: 'Promemoria automatico a chi si ferma prima di pagare.' },
      { icon: 'chat', title: 'Raccolta contatti per riacquisto', body: 'Chi compra una volta resta un contatto a cui riscrivere.' },
    ],
    howWeWork: [
      { n: '1', title: 'Analisi', duration: '1 settimana', body: 'Guardiamo lo store attuale (se c’è), il catalogo e come vendete oggi.' },
      { n: '2', title: 'Progetto', duration: '1-2 settimane', body: 'Struttura del catalogo e del percorso d’acquisto. Vedete il mockup prima dello sviluppo.' },
      { n: '3', title: 'Costruzione', duration: '3-5 settimane', body: 'Sviluppo dello store, catalogo, pagamenti e spedizioni. Avanzamento visibile ogni settimana.' },
      { n: '4', title: 'Lancio e dopo', duration: '3 mesi', body: 'Online, formazione al team, assistenza inclusa per sistemare ciò che i dati dicono.' },
    ],
    howWeWorkNote: 'In media: 6-9 settimane dal via al lancio.',
    comparisonTable: {
      competitorA: 'Web agency generalista',
      competitorB: 'Shopify fai-da-te (temi)',
      rows: [
        { label: 'Conosce il settore', mg: 'Solo questo', competitorA: 'No', competitorB: '—' },
        { label: 'Store curato', mg: 'Sì', competitorA: 'Sì', competitorB: 'Dipende' },
        { label: 'Abbonamenti / ricorrenza', mg: 'Sì', competitorA: 'A volte', competitorB: 'Con app di terzi' },
        { label: 'Spedizione multi-zona configurata', mg: 'Sì', competitorA: 'A volte', competitorB: 'Manuale' },
        { label: 'Chi vi risponde', mg: 'Chi lavora sul progetto', competitorA: 'Un account', competitorB: 'Nessuno' },
        { label: 'Dopo il lancio', mg: '3 mesi inclusi', competitorA: 'Progetto chiuso', competitorB: 'Da soli' },
      ],
      closingLine: 'La differenza non è tecnica. È che quando dite "wine club", "annata" o "DOP" non dobbiamo chiedere cosa significa.',
    },
    investment: {
      eyebrow: 'Prezzi pubblicati',
      heading: 'Quanto costa vendere online il vostro prodotto',
      subheading: 'Vendere diretto vale più che vendere di più.',
      plans: [
        {
          ...pricing.ecommerce,
          offerName: 'E-commerce per vendita diretta',
          offerDescription: 'Uno store che tiene il margine e tiene il cliente.',
          benefits: [
            'Catalogo fino a 30 prodotti, schede scritte da noi',
            'Formati e bundle',
            'Listini differenziati B2B',
            'Spedizioni Italia ed estero configurate',
            'Pagamenti e recupero carrelli abbandonati',
            '2 ore di formazione',
          ],
          exclusions: ['Oltre 30 prodotti (+8€/prodotto)', 'Traduzioni', 'Integrazione gestionale'],
          reassurances: [
            'Prezzi pubblicati: quello che leggete è quello che pagate',
            '3 mesi di assistenza inclusi dopo il lancio',
            'Tutto resta vostro',
          ],
          closing: 'Cifra precisa dopo una call di 20 minuti. Se non ha senso farlo, ve lo diciamo.',
        },
      ],
    },
    faqs: [
      { q: 'Shopify o Shopify Plus: come si sceglie?', a: 'Dipende dal volume di vendite e dalla complessità delle integrazioni: lo valutiamo insieme in fase di analisi.' },
      { q: 'Potete migrare il mio store esistente?', a: 'Sì, valutiamo caso per caso cosa migrare e cosa ricostruire da zero per performance migliori.' },
      { q: 'Gestite anche il catalogo prodotti?', a: 'Impostiamo la struttura; l’aggiornamento quotidiano del catalogo resta tuo, con formazione inclusa.' },
      { q: 'Siete in tre. Riuscite a seguirci?', a: 'Proprio perché siamo in tre prendiamo pochi progetti alla volta. Chi vi risponde è chi lavora sul vostro store, non un account che gira la mail a qualcun altro.' },
      { q: 'Lavorate solo in Umbria?', a: 'Siamo a Perugia ma lavoriamo in tutta Italia. Per chi è entro due o tre ore veniamo di persona all’inizio e al lancio.' },
    ],
    relatedSlugs: ['restyling-ottimizzazione', 'automazioni-ai'],
  },
  {
    slug: 'siti-web-contatti',
    n: '03',
    tag: 'WEB',
    icon: 'web',
    title: 'Siti web che generano contatti',
    seoTitle: 'Siti Web per Cantine, Frantoi e Agriturismi',
    seoDescription:
      'Siti responsive, veloci e ottimizzati SEO per farsi trovare online. Progettati sul tuo settore, non su un template generico per PMI qualsiasi.',
    heroImage: '/images/servizi/siti-web-contatti-hero.jpg',
    body: 'Siti pensati per far arrivare chiamate, messaggi e richieste di preventivo. Struttura, copy e call-to-action guidano il visitatore fino all’azione.',
    resultNote: 'Più richieste di contatto e prenotazioni dirette, non solo visite passive.',
    tesi: 'Il sito non è una vetrina, è il canale che raccoglie richieste mentre dormite.',
    problemBlock: {
      eyebrow: 'Ci risulta che vada più o meno così',
      paragraphs: [
        'Qualcuno vi cerca. Vi trova, gli piacete, vuole prenotare una degustazione. Sono le nove di sera di una domenica.',
        'Sul sito c’è una mail. La scrive. Poi, mentre aspetta, apre un’altra scheda e prenota da qualcun altro che gli ha dato una conferma in trenta secondi.',
        'Voi quella mail la leggete lunedì mattina. E non saprete mai quante ne sono andate così.',
      ],
      image: '/images/servizi/siti-web-contatti-problema.webp',
      imageAlt: 'Vigneto al tramonto, l’ora in cui arrivano le richieste che si perdono',
    },
    changeBlock: {
      heading: 'Cosa cambia con un sito costruito per il vostro settore',
      paragraphs: [
        'Le richieste non passano più dalla mail. Chi vuole prenotare vede le date libere, sceglie, paga la caparra e riceve la conferma subito. Anche di domenica sera.',
        'Chi arriva sul sito capisce in pochi secondi cosa fate, cosa può comprare e cosa può prenotare — senza dover cercare.',
        'E chi compra una volta non sparisce: resta un contatto a cui potete scrivere quando esce l’annata nuova.',
      ],
      image: '/images/servizi/siti-web-contatti-cambia.webp',
      imageAlt: 'Degustazione guidata con più calici in fila, prenotata comodamente in cantina',
    },
    includes: [
      { icon: 'web', title: 'Struttura e pagine', body: 'Progettate sul vostro percorso di vendita, non su un template.' },
      { icon: 'book', title: 'Contenuti e racconto', body: 'Testi, schede prodotto, la vostra storia. Scritti, non riempiti.' },
      { icon: 'calendar', title: 'Prenotazioni online', body: 'Calendario, pagamenti, promemoria automatici.' },
      { icon: 'compass', title: 'Trovabilità', body: 'SEO di base, Google Business, mappe, struttura leggibile dai motori.' },
      { icon: 'target', title: 'Formazione', body: 'Due ore col vostro team, più i video per rivederle.' },
      { icon: 'lock', title: 'Assistenza 3 mesi', body: 'Correzioni, modifiche, monitoraggio dopo il lancio.' },
    ],
    howWeWork: [
      { n: '1', title: 'Analisi', duration: '1 settimana', body: 'Guardiamo il sito attuale, i numeri, i competitor della zona. Vi diciamo cosa vi sta costando.' },
      { n: '2', title: 'Progetto', duration: '1-2 settimane', body: 'Struttura e contenuti. Vedete il mockup prima che si scriva una riga di codice.' },
      { n: '3', title: 'Costruzione', duration: '2-3 settimane', body: 'Sviluppo e contenuti. Vedete l’avanzamento ogni settimana.' },
      { n: '4', title: 'Lancio e dopo', duration: '3 mesi', body: 'Online, formazione al team, e restiamo a sistemare ciò che i dati dicono.' },
    ],
    howWeWorkNote: 'In media: 5-7 settimane dal via al lancio.',
    comparisonTable: {
      competitorA: 'Web agency generalista',
      competitorB: 'Fai da te (Wix, temi)',
      rows: [
        { label: 'Conosce il settore', mg: 'Solo questo', competitorA: 'No', competitorB: '—' },
        { label: 'Sito curato', mg: 'Sì', competitorA: 'Sì', competitorB: 'Dipende' },
        { label: 'Prenotazioni integrate', mg: 'Sì', competitorA: 'A volte', competitorB: 'No' },
        { label: 'Vendita diretta', mg: 'Sì', competitorA: 'A volte', competitorB: 'Base' },
        { label: 'Wine club / ricorrenza', mg: 'Sì', competitorA: 'No', competitorB: 'No' },
        { label: 'Chi vi risponde', mg: 'Chi lavora sul progetto', competitorA: 'Un account', competitorB: 'Nessuno' },
        { label: 'Dopo il lancio', mg: '3 mesi inclusi', competitorA: 'Progetto chiuso', competitorB: 'Da soli' },
      ],
      closingLine: 'La differenza non è tecnica. È che quando dite "wine club", "annata" o "DOP" non dobbiamo chiedere cosa significa.',
    },
    investment: {
      eyebrow: 'Prezzi pubblicati',
      heading: 'Quanto costa un sito per la vostra attività',
      subheading: 'Nessun listino nascosto, nessun "dipende" all’infinito.',
      plans: [
        {
          ...pricing.sitoEssenziale,
          offerDescription: 'Un sito su misura che vi fa trovare e raccogliere richieste.',
          benefits: [
            'Fino a 6 pagine, design su misura',
            'SEO tecnica di base e Google Business configurati',
            'Form di contatto e WhatsApp',
            'Tracciamento delle richieste',
            'Veloce da mobile',
            '30 giorni di assistenza inclusi',
          ],
          exclusions: ['Contenuti scritti da noi (li fornite voi)', 'Prenotazioni online', 'E-commerce', 'Traduzioni'],
          reassurances: ['Prezzi pubblicati: quello che leggete è quello che pagate', 'Dominio, codice e accessi restano vostri'],
          closing: 'Cifra precisa dopo una call di 20 minuti.',
        },
        {
          ...pricing.sitoPrenotazioni,
          offerDescription: 'Un sito che raccoglie richieste e prenotazioni anche quando siete in vigna, in frantoio o in accoglienza.',
          benefits: [
            'Tutto il sito essenziale, pagine senza limite',
            'Calendario prenotazioni con caparra',
            'Testi e schede prodotto scritti da noi',
            'Promemoria automatici',
            '2 ore di formazione',
          ],
          exclusions: ['E-commerce completo', 'Traduzioni', 'Integrazione gestionale'],
          reassurances: [
            'Prezzi pubblicati: quello che leggete è quello che pagate',
            '3 mesi di assistenza inclusi dopo il lancio',
            'Dominio, codice e accessi restano vostri',
          ],
          closing: 'Cifra precisa dopo una call di 20 minuti. Se non ha senso farlo, ve lo diciamo.',
        },
      ],
    },
    faqs: [
      { q: 'Abbiamo già un sito. Dobbiamo rifarlo da zero?', a: 'Spesso no. A volte conviene tenerlo e aggiungerci sopra quello che manca — prenotazioni, shop, raccolta contatti. Ve lo diciamo dopo averlo guardato, e se la risposta è "va bene così" ve la diciamo lo stesso.' },
      { q: 'Siete in tre. Riuscite a seguirci?', a: 'Proprio perché siamo in tre prendiamo pochi progetti alla volta. Chi vi risponde al telefono è chi lavora sul vostro sito, non un account che poi gira la mail a qualcun altro.' },
      { q: 'Quanto ci vuole?', a: '5-7 settimane per un sito. Se serve anche lo shop, 8-10.' },
      { q: 'Lavorate solo in Umbria?', a: 'Siamo a Perugia ma lavoriamo in tutta Italia. Per chi è entro due o tre ore veniamo di persona all’inizio e al lancio: su queste cose vedere i posti cambia il lavoro.' },
      { q: 'E dopo il lancio ci lasciate soli?', a: 'Tre mesi di assistenza sono inclusi. Vi formiamo perché possiate gestirlo da soli, e se poi volete continuare con noi si può.' },
    ],
    relatedSlugs: ['restyling-ottimizzazione', 'consulenza-strategica'],
  },
  {
    slug: 'restyling-ottimizzazione',
    n: '04',
    tag: 'RESTYLING',
    icon: 'refresh',
    title: 'Restyling e ottimizzazione',
    seoTitle: 'Restyling e Ottimizzazione Siti Web',
    seoDescription:
      'Il tuo sito è lento o datato? Lo miglioriamo dove serve: design, velocità, SEO tecnica e conversioni. Da vetrina passiva a canale che vende.',
    heroImage: '/images/servizi/restyling-ottimizzazione-hero.jpg',
    body: 'Il tuo sito è vecchio o non converte? Lo rifacciamo o lo miglioriamo dove serve: grafica, contenuti, performance e SEO tecnica.',
    resultNote: 'Un sito più veloce, più chiaro, che riprende a produrre contatti o vendite.',
    tesi: 'Spesso non serve rifare, serve aggiungere il pezzo che manca.',
    problemBlock: {
      eyebrow: 'Ci risulta che vada più o meno così',
      paragraphs: [
        'Il vostro sito probabilmente non è il problema.',
        'Le web agency vi diranno di rifarlo. È normale: è quello che vendono.',
        'Ma nella maggior parte dei casi il sito che avete regge. Quello che manca è un pezzo sopra: le prenotazioni, lo shop, un modo per raccogliere i contatti di chi passa. Costa una frazione, si fa in poche settimane, e non buttate via quello che avete già pagato.',
        'Se invece rifarlo serve davvero, ve lo diciamo. Ma solo dopo averlo guardato.',
      ],
      image: '/images/servizi/restyling-ottimizzazione-problema.webp',
      imageAlt: 'Vecchia facciata di un edificio italiano con intonaco consumato, come un sito da rinnovare',
    },
    changeBlock: {
      heading: 'Cosa cambia con un intervento mirato',
      paragraphs: [
        'L’audit vi dice con esattezza cosa tenere, cosa cambiare e cosa manca — non un rifacimento alla cieca.',
        'Il posizionamento SEO che avete già costruito resta intatto: redirect e struttura si gestiscono con attenzione, non si buttano via.',
        'Il sito riparte a produrre contatti o vendite senza che dobbiate rifare tutto da capo.',
      ],
      image: '/images/servizi/restyling-ottimizzazione-cambia.webp',
      imageAlt: 'Casale ristrutturato, l’intervento mirato che serviva',
    },
    includes: [
      { icon: 'compass', title: 'Audit del sito esistente', body: 'Cosa tenere, cosa cambiare, cosa manca.' },
      { icon: 'web', title: 'Restyling grafico', body: 'Coerente con il brand, non un template diverso.' },
      { icon: 'refresh', title: 'Velocità e performance', body: 'Core Web Vitals, immagini, caching.' },
      { icon: 'book', title: 'Contenuti e SEO', body: 'Aggiornamento struttura e testi dove serve.' },
      { icon: 'target', title: 'Percorso di conversione', body: 'Rivisto dove il sito perde richieste.' },
    ],
    howWeWork: [
      { n: '1', title: 'Analisi', duration: '3-5 giorni', body: 'Audit tecnico e di contenuto: cosa tenere, cosa cambiare, cosa manca.' },
      { n: '2', title: 'Progetto', duration: '3-5 giorni', body: 'Vi mostriamo cosa interverremmo e in che ordine, prima di toccare nulla.' },
      { n: '3', title: 'Intervento', duration: '1-3 settimane', body: 'Sviluppo dell’intervento concordato, con redirect gestiti per non perdere posizionamento.' },
      { n: '4', title: 'Lancio e dopo', duration: 'a richiesta', body: 'Online, e potete aggiungere l’assistenza continuativa se serve.' },
    ],
    howWeWorkNote: 'In media: 2-4 settimane dal via al lancio, a seconda dell’intervento.',
    comparisonTable: {
      competitorA: 'Rifare tutto con un’agenzia',
      competitorB: 'Lasciare com’è',
      rows: [
        { label: 'Conosce il settore', mg: 'Solo questo', competitorA: 'No', competitorB: '—' },
        { label: 'Mantiene il posizionamento SEO', mg: 'Sì', competitorA: 'A volte', competitorB: 'Sì, ma non migliora' },
        { label: 'Costo', mg: 'Proporzionato all’intervento', competitorA: 'Come un sito nuovo', competitorB: 'Zero, ma zero risultati nuovi' },
        { label: 'Tempi', mg: '2-4 settimane', competitorA: '2-4 mesi', competitorB: '—' },
        { label: 'Chi vi risponde', mg: 'Chi lavora sul progetto', competitorA: 'Un account', competitorB: 'Nessuno' },
      ],
      closingLine: 'La differenza non è tecnica. È che quando dite "wine club", "annata" o "DOP" non dobbiamo chiedere cosa significa.',
    },
    investment: {
      eyebrow: 'Prezzi pubblicati',
      heading: 'Quanto costa sistemare quello che avete già',
      subheading: 'Spesso non serve rifare. Serve aggiungere il pezzo che manca.',
      plans: [
        {
          ...pricing.restylingMirato,
          offerName: 'Intervento mirato',
          offerDescription: 'Prenotazioni, shop o raccolta contatti aggiunti al sito che avete già.',
          benefits: [
            'Analisi del sito attuale',
            'Un intervento mirato: prenotazioni, shop base o raccolta contatti',
            '2-3 settimane invece di due mesi',
          ],
          exclusions: ['Redesign completo', 'Più interventi insieme'],
          reassurances: [
            'Prezzi pubblicati: quello che leggete è quello che pagate',
            'Redirect e SEO gestiti per non perdere posizionamento',
            `Potete aggiungere l’assistenza continuativa da ${pricing.assistenzaMensile.price}€/mese dopo l’intervento`,
          ],
          closing: 'Se invece rifarlo conviene davvero, ve lo diciamo — anche se per noi è un lavoro più piccolo.',
        },
      ],
    },
    faqs: [
      { q: 'Perdo il posizionamento SEO che ho già?', a: 'No, gestiamo redirect e struttura con attenzione per mantenere (o migliorare) il posizionamento esistente.' },
      { q: 'Devo rifare tutti i contenuti?', a: 'Solo dove serve: valutiamo insieme cosa conservare e cosa riscrivere in fase di audit.' },
      { q: 'Siete in tre. Riuscite a seguirci?', a: 'Proprio perché siamo in tre prendiamo pochi progetti alla volta. Chi vi risponde è chi lavora sul vostro sito, non un account che gira la mail a qualcun altro.' },
      { q: 'Quanto dura l’intervento?', a: 'Dalle 2 alle 4 settimane in media, a seconda che sia un intervento mirato o un restyling completo.' },
      { q: 'Lavorate solo in Umbria?', a: 'Siamo a Perugia ma lavoriamo in tutta Italia. Per chi è entro due o tre ore veniamo di persona dove serve.' },
    ],
    relatedSlugs: ['siti-web-contatti', 'ecommerce-shopify'],
  },
  {
    slug: 'automazioni-ai',
    n: '05',
    tag: 'INTEGRAZIONI',
    icon: 'integration',
    title: 'AI integration nei tuoi flussi',
    seoTitle: 'AI Integration nei Processi Agroalimentari',
    seoDescription:
      'Integriamo l’AI nei processi che già usi: preventivi, customer care, contenuti, automazioni operative. Meno lavoro manuale, più efficienza reale.',
    heroImage: '/images/servizi/ai-integration-hero.jpg',
    body: 'Colleghiamo l’intelligenza artificiale ai processi che già usi: preventivi, customer care, aggiornamento contenuti, automazioni operative.',
    resultNote: 'Strumenti che già usi, collegati tra loro, con meno lavoro manuale di travaso dati.',
    whatIsIt:
      'Se hai già sistemi e strumenti (email, gestionale, CRM, spedizioni), spesso il problema non è la mancanza di tecnologia ma la mancanza di collegamento tra i pezzi. Integriamo l’AI nei flussi esistenti invece di sostituirli tutti.',
    whatIsItMore: [
      'Lavoriamo con le API degli strumenti che già usi — email, gestionale, CRM, spedizioni — invece di proporre l’ennesima piattaforma da imparare. Dove un’integrazione diretta non esiste, valutiamo alternative prima di chiederti di cambiare strumento.',
      'I modelli AI (OpenAI, Anthropic o Gemini, a seconda del caso) entrano nel flusso solo dove servono davvero: un quiz, una raccomandazione, un filtro anti-abbandono. I dati restano centralizzati in un unico database, non sparsi tra automazioni scollegate tra loro.',
    ],
    quickFacts: [
      { label: 'Tempo di attivazione', value: '2-4 settimane per integrazione' },
      { label: 'Approccio', value: 'API REST — colleghiamo, non sostituiamo' },
      { label: 'Intelligenza artificiale', value: 'OpenAI, Anthropic, Gemini' },
      { label: 'Canali collegabili', value: 'Email, WhatsApp Business API, CRM, e-commerce' },
      { label: 'Dati', value: 'Centralizzati su database dedicato' },
    ],
    bullets: [
      'Automazioni tra strumenti che già usi',
      'Quiz o raccomandazioni intelligenti per i tuoi clienti',
      'Prevenzione abbandono (churn) su abbonamenti e wine club',
      'Tracking e comunicazioni automatizzate',
      'Centralizzazione dei dati cliente',
    ],
    perSettoreExtra: {
      'wine-viticulture': 'Wine club automation: pagamenti ricorrenti, quiz di preferenze, prevenzione abbandono.',
      'oleifici-food-tech': 'Automazione tra e-commerce e comunicazione post-vendita per l’abbonamento olio.',
      'wine-hospitality-agriturismi': 'Automazioni WhatsApp collegate al booking, senza intervento manuale.',
    },
    caseStudySlug: 'wine-club-pro',
    caseStudyNote: 'Wine Club Pro, sviluppato per Azienda Rossi, integra pagamenti ricorrenti, un quiz AI di preferenze e automazioni anti-abbandono: 85% di retention dal primo al dodicesimo mese.',
    testimonialName: 'Giulia',
    technicalPoints: [
      'Integrazioni via API REST con gli strumenti che già usi',
      'Automazioni email e messaggistica (WhatsApp Business API)',
      'Modelli AI: OpenAI, Anthropic, Gemini per raccomandazioni o quiz',
      'Dati centralizzati in un unico posto',
    ],
    faqs: [
      { q: 'Devo cambiare i software che già uso?', a: 'Di norma no: l’obiettivo è collegarli, non sostituirli, salvo che uno strumento sia davvero un limite.' },
      { q: 'Funziona con qualsiasi gestionale?', a: 'Dipende dalla disponibilità di API o integrazioni: lo verifichiamo nella fase di analisi.' },
    ],
    relatedSlugs: ['siti-web-contatti', 'consulenza-strategica'],
  },
  {
    slug: 'consulenza-strategica',
    n: '06',
    tag: 'CONSULENZA',
    icon: 'compass',
    premium: true,
    title: 'Consulenza strategica',
    seoTitle: 'Consulenza Strategica Digitale Agroalimentare',
    seoDescription:
      'Analizziamo il tuo progetto, individuiamo le priorità reali e definiamo una roadmap concreta. Il punto di partenza prima di scegliere la tecnologia.',
    heroImage: '/images/servizi/consulenza-strategica-hero.jpg',
    body: 'Analizziamo il tuo progetto, individuiamo i punti critici e definiamo una roadmap concreta per crescere online. Niente fuffa, solo priorità chiare.',
    resultNote: 'Priorità chiare su cosa fare per primo, e perché.',
    tesi: 'Prima di spendere, capire dove state perdendo.',
    problemBlock: {
      eyebrow: 'Ci risulta che vada più o meno così',
      paragraphs: [
        'Il problema non è quasi mai il sito.',
        'È che nessuno ha mai guardato i numeri insieme. Quante richieste arrivano e quante diventano clienti. Quanto vale un cliente nei due anni dopo il primo acquisto. Quale canale porta le persone che spendono di più.',
        'Senza questi numeri, qualsiasi cosa costruiate è una scommessa.',
      ],
      image: '/images/servizi/consulenza-strategica-problema.webp',
      imageAlt: 'Appunti e pianificazione in vigna, prima di decidere cosa costruire',
    },
    changeBlock: {
      heading: 'Cosa cambia con una direzione chiara',
      paragraphs: [
        'Sapete cosa fare prima e cosa dopo, non un elenco di funzionalità possibili senza un ordine.',
        'Ogni euro investito dopo la consulenza va dove serve davvero, non dove sembrava urgente.',
        'Se dopo l’analisi non ha senso procedere insieme, ve lo diciamo apertamente: la direzione resta vostra comunque.',
      ],
      image: '/images/servizi/consulenza-strategica-cambia.webp',
      imageAlt: 'Cassette di vendemmia ordinate, come le priorità dopo l’analisi',
    },
    includes: [
      { icon: 'compass', title: 'Analisi del sito e dei numeri attuali', body: 'Richieste, conversioni, dati che già avete.' },
      { icon: 'target', title: 'Analisi dei competitor della zona', body: 'Chi altro c’è, e cosa fa diversamente.' },
      { icon: 'chart', title: 'Dove si perde e quanto vale', body: 'Un quadro concreto, non intuizioni.' },
      { icon: 'refresh', title: 'Un piano con le priorità in ordine', body: 'Cosa fare prima, cosa dopo, e perché.' },
      { icon: 'book', title: 'Report scritto che resta vostro', body: 'Utile anche se poi decidete di non proseguire con noi.' },
    ],
    howWeWork: [
      { n: '1', title: 'Prima call', duration: 'gratuita', body: 'Ci raccontate il business, capiamo se ha senso procedere.' },
      { n: '2', title: 'Analisi', duration: 'mezza giornata da voi o due call', body: 'Guardiamo sito, numeri e concorrenza diretta.' },
      { n: '3', title: 'Documento con roadmap', duration: 'circa 1 settimana', body: 'Priorità ordinate, non un elenco di funzionalità.' },
      { n: '4', title: 'Decisione', duration: 'nessun vincolo', body: 'Se ha senso proseguire insieme lo facciamo; se no, la direzione resta vostra.' },
    ],
    howWeWorkNote: 'Formato: mezza giornata da voi o due call + documento finale.',
    comparisonTable: {
      competitorA: 'Nessuna consulenza (si decide a intuito)',
      competitorB: 'Consulente generalista',
      rows: [
        { label: 'Conosce il settore', mg: 'Solo questo', competitorA: '—', competitorB: 'No' },
        { label: 'Guarda i numeri reali', mg: 'Sì', competitorA: 'No', competitorB: 'A volte' },
        { label: 'Priorità ordinate, non funzionalità', mg: 'Sì', competitorA: '—', competitorB: 'A volte' },
        { label: 'Vi dice se non serve procedere', mg: 'Sì', competitorA: '—', competitorB: 'Raramente' },
        { label: 'Chi vi risponde', mg: 'Chi lavora sul progetto', competitorA: '—', competitorB: 'Un account' },
      ],
      closingLine: 'La differenza non è tecnica. È che quando dite "wine club", "annata" o "DOP" non dobbiamo chiedere cosa significa.',
    },
    investment: {
      eyebrow: 'Prezzi pubblicati',
      heading: 'Quanto costa capire dove state perdendo',
      subheading: 'Una direzione chiara, prima di spendere in tecnologia.',
      plans: [
        {
          ...pricing.consulenzaOrientamento,
          offerDescription: '2 ore in call.',
          benefits: [
            'Analisi del sito e dei canali attuali',
            'Dove si perdono le richieste',
            'Tre priorità in ordine',
            'Sintesi scritta',
          ],
        },
        {
          ...pricing.consulenzaCompleta,
          offerDescription: 'Una giornata da voi.',
          benefits: [
            'Tutto quello della formula precedente',
            'Analisi dei competitor della zona',
            'Piano scritto con stime e priorità',
          ],
        },
        {
          ...pricing.percorso3Mesi,
          offerDescription: 'Analisi completa più tre mesi di supporto continuativo.',
          benefits: [
            'Analisi completa inclusa',
            'Un incontro al mese',
            'Priorità riviste ogni mese',
            'Supporto WhatsApp tra un incontro e l’altro',
          ],
        },
      ],
      note: 'Se dopo la consulenza partite con un progetto, il costo viene scalato interamente dal preventivo. Nessun vincolo a continuare insieme. Trasferte entro 100 km incluse. Cifra precisa dopo la prima call, gratuita e senza impegno.',
    },
    faqs: [
      { q: 'La consulenza è vincolante per poi lavorare insieme?', a: 'No. Ti diciamo con onestà se ha senso proseguire; se la risposta è no, hai comunque una direzione più chiara.' },
      { q: 'Quanto dura?', a: 'Dipende dalla complessità del progetto: lo definiamo nella prima chiamata conoscitiva.' },
      { q: 'Cosa ricevo alla fine?', a: 'Un quadro chiaro delle priorità e, se decidiamo di proseguire, i prossimi passi concreti del progetto.' },
      { q: 'Siete in tre. Riuscite a seguirci?', a: 'Proprio perché siamo in tre prendiamo pochi progetti alla volta. Chi vi risponde è chi lavora sul vostro caso, non un account che gira la mail a qualcun altro.' },
      { q: 'Lavorate solo in Umbria?', a: 'Siamo a Perugia ma lavoriamo in tutta Italia. Per chi è entro due o tre ore veniamo di persona dove serve.' },
    ],
    relatedSlugs: ['automazioni-ai', 'siti-web-contatti'],
  },
  {
    slug: 'seo-geo-strategy',
    n: '07',
    tag: 'SEO & GEO',
    icon: 'target',
    title: 'SEO & GEO Strategy',
    seoTitle: 'SEO & GEO Strategy per Cantine, Frantoi e Agriturismi',
    seoDescription:
      'Struttura tecnica, contenuti e presenza nei motori di ricerca e nell’AI, per portare traffico e contatti qualificati a cantine, frantoi e agriturismi.',
    heroImage: '/images/servizi/seo-geo-strategy-hero.jpg',
    body: 'Struttura tecnica, contenuti e presenza nei motori di ricerca e nell’AI, per portare traffico e contatti qualificati.',
    resultNote: 'Più persone che cercano la tua cantina, il tuo olio o il tuo agriturismo ti trovano — su Google e sull’AI.',
    tesi: 'Fatti trovare da chi cerca davvero la tua cantina, il tuo olio, il tuo agriturismo.',
    problemBlock: {
      eyebrow: 'Ci risulta che vada più o meno così',
      paragraphs: [
        'Il sito c’è, ma per chi cerca "cantina" più la vostra zona, o "agriturismo" più un’occasione precisa, non compare mai nelle prime posizioni.',
        'Chi chiede a ChatGPT o Perplexity di consigliargli una cantina o un agriturismo nella vostra zona, oggi, probabilmente non vi cita. E non lo sapete nemmeno, perché nessuno lo controlla.',
        'Il sito è lento o strutturato male dal punto di vista tecnico, e questo pesa sul posizionamento più di quanto pensiate.',
        'Senza numeri — impressioni, posizione media, clic — ogni intervento SEO è una scommessa: non sapete se sta funzionando finché non è tardi per correggere.',
      ],
      image: '/images/servizi/seo-geo-strategy-problema.jpg',
      imageAlt: 'Strada di campagna che si perde nella nebbia, come un sito che nessuno trova',
    },
    changeBlock: {
      heading: 'Cosa cambia quando vi trovano davvero',
      paragraphs: [
        'Chi cerca il vostro prodotto o la vostra zona vi trova nelle prime posizioni — non un grossista, non un aggregatore come Booking.',
        'Quando qualcuno chiede a ChatGPT o a Google AI Overview consigli sul vostro settore e territorio, il vostro nome può comparire nella risposta, non solo tra i link blu di una ricerca classica.',
        'Sapete esattamente cosa sta funzionando — quali pagine, quali ricerche, quale posizione — non a sensazione.',
      ],
      image: '/images/servizi/seo-geo-strategy-cambia.jpg',
      imageAlt: 'Cartello di legno che indica una direzione chiara, come un sito finalmente trovabile',
    },
    includes: [
      { icon: 'target', title: 'Audit tecnico e ricerca keyword', body: 'Velocità, indicizzazione, e le parole chiave reali di zona, prodotto e varietà.' },
      { icon: 'book', title: 'SEO on-page e contenuti', body: 'Pagine ottimizzate per chi cerca per comprare, per prenotare o solo per informarsi.' },
      { icon: 'compass', title: 'SEO locale', body: 'Google Business Profile e pagine di zona, coerenti con il territorio che presidiate.' },
      { icon: 'chat', title: 'Visibilità nei motori AI (GEO)', body: 'Contenuti e dati strutturati pensati per essere citati da ChatGPT, Perplexity e AI Overview.' },
      { icon: 'chart', title: 'Monitoraggio e reportistica', body: 'Dashboard con Search Console e GA4, KPI chiari, aggiornamenti periodici.' },
    ],
    howWeWork: [
      { n: '1', title: 'Audit e obiettivi', duration: '1 settimana', body: 'Guardiamo sito, posizionamento attuale e cosa cercano davvero i vostri clienti.' },
      { n: '2', title: 'Strategia su keyword e territorio', duration: '1 settimana', body: 'Priorità di parole chiave, intent e pagine di zona su cui lavorare per prime.' },
      { n: '3', title: 'Ottimizzazione tecnica e contenuti', duration: '3-6 settimane', body: 'Interventi on-page, dati strutturati e contenuti scritti o rivisti.' },
      { n: '4', title: 'Monitoraggio continuo', duration: 'mese su mese', body: 'Dashboard, aggiustamenti e verifica di cosa dicono di voi i motori AI.' },
    ],
    howWeWorkNote: 'In media: 4-6 settimane per i primi interventi, poi lavoro continuativo mese su mese.',
    comparisonTable: {
      competitorA: 'Nessun lavoro SEO (si spera in Google)',
      competitorB: 'Agenzia SEO generalista',
      rows: [
        { label: 'Conosce il settore', mg: 'Solo questo', competitorA: '—', competitorB: 'No' },
        { label: 'Lavora anche sulla visibilità AI (GEO)', mg: 'Sì', competitorA: '—', competitorB: 'Raramente' },
        { label: 'SEO locale su territorio e prodotto', mg: 'Sì', competitorA: '—', competitorB: 'Generica' },
        { label: 'Dashboard e numeri reali', mg: 'Sì', competitorA: 'No', competitorB: 'A volte' },
        { label: 'Chi vi risponde', mg: 'Chi lavora sul progetto', competitorA: '—', competitorB: 'Un account' },
      ],
      closingLine: 'La differenza non è tecnica. È che quando dite "wine club", "annata" o "DOP" non dobbiamo chiedere cosa significa.',
    },
    investment: {
      eyebrow: 'Prezzi pubblicati',
      heading: 'Quanto costa farsi trovare davvero',
      subheading: 'Un audit per capire dove siete, poi un lavoro continuativo per restare visibili.',
      plans: [
        {
          ...pricing.seoGeoAudit,
          offerDescription: 'Il punto di partenza: dove siete oggi e cosa fare prima.',
          benefits: [
            'Audit tecnico completo del sito',
            'Ricerca keyword su zona, prodotto e intent',
            'Verifica di cosa dicono di voi ChatGPT e Google AI Overview oggi',
            'Report scritto con le priorità in ordine',
          ],
          exclusions: ['Interventi tecnici sul sito', 'Gestione continuativa'],
          reassurances: ['Prezzi pubblicati: quello che leggete è quello che pagate', 'Resta vostro anche se poi non proseguite con noi'],
          closing: 'Se dopo l’audit partite con la gestione continuativa, il costo viene scalato dal primo mese.',
        },
        {
          ...pricing.seoGeoContinuativo,
          offerDescription: 'Lavoro mese su mese su contenuti, SEO locale e presenza nei motori AI.',
          benefits: [
            'SEO on-page e contenuti aggiornati ogni mese',
            'SEO locale: Google Business Profile e pagine di zona',
            'Dati strutturati e contenuti pensati per i motori AI',
            'Dashboard mensile con Search Console e GA4',
            'Priorità riviste ogni mese',
          ],
          exclusions: ['Redazione di grandi volumi di contenuti da zero (si valuta a parte)'],
          closing: 'Nessun vincolo minimo rigido: se dopo qualche mese non ha senso continuare, ve lo diciamo noi per primi.',
        },
      ],
      note: 'Cifra precisa dopo una call di 20 minuti: dipende dallo stato attuale del sito e dal territorio da coprire. Se non ha senso partire subito con il continuativo, ve lo diciamo.',
    },
    faqs: [
      { q: 'Quanto tempo serve per vedere risultati SEO?', a: 'I primi segnali (impressioni, posizioni) si vedono in 4-8 settimane; risultati solidi su ricerche competitive richiedono in genere 3-6 mesi di lavoro continuativo. Chi promette risultati in pochi giorni non sta facendo SEO.' },
      { q: 'La SEO funziona anche per una piccola cantina o un agriturismo a conduzione familiare?', a: 'Sì, spesso funziona meglio: le ricerche locali e di nicchia — varietà, zona, tipo di esperienza — hanno meno concorrenza di quelle generiche, ed è lì che si vince.' },
      { q: 'Cosa significa "GEO" e perché conta anche per il mio settore?', a: 'GEO (Generative Engine Optimization) vuol dire farsi citare da ChatGPT, Perplexity e Google AI Overview quando qualcuno chiede consigli sul vostro prodotto o territorio. Sempre più persone partono da lì invece che da una ricerca classica.' },
      { q: 'Serve rifare il sito per fare SEO o si può lavorare su quello esistente?', a: 'Nella maggior parte dei casi si lavora su quello che c’è: struttura, contenuti e velocità. Solo se il sito è davvero un limite tecnico proponiamo un intervento più profondo (vedi restyling).' },
      { q: 'Gestite anche la parte tecnica (schema, velocità) o solo i contenuti?', a: 'Entrambe: dati strutturati, velocità e indicizzazione fanno parte del lavoro tanto quanto i contenuti. Una cosa senza l’altra funziona a metà.' },
    ],
    relatedSlugs: ['siti-web-contatti', 'restyling-ottimizzazione'],
  },
  {
    slug: 'brand-identity',
    n: '08',
    tag: 'BRAND',
    icon: 'palette',
    title: 'Brand Identity',
    seoTitle: 'Brand Identity per Cantine, Frantoi e Agriturismi',
    seoDescription:
      'Logo, palette, tono di voce e materiali coordinati: un’identità che comunica la qualità del tuo territorio prima ancora delle parole.',
    heroImage: '/images/servizi/brand-identity-hero.jpg',
    body: 'Logo, palette, tono di voce e materiali coordinati: un’identità che comunica la qualità del tuo territorio prima ancora delle parole.',
    resultNote: 'Un’immagine coerente su sito, social, etichette e materiali — riconoscibile ovunque vi si incontri.',
    tesi: 'Un’identità che racconta la qualità del tuo territorio, prima ancora di aprire bocca.',
    problemBlock: {
      eyebrow: 'Ci risulta che vada più o meno così',
      paragraphs: [
        'Il logo esiste, ma probabilmente non è mai stato pensato per funzionare piccolo, in bianco e nero, o su un’icona social.',
        'Sito, etichette e materiali stampati sembrano di aziende diverse. Non c’è una palette definita: ogni volta si va a occhio.',
        'Ogni fornitore — il grafico, lo stampatore, chi gestisce i social — interpreta il brand a modo suo, perché nessuna linea guida gli dice come farlo.',
        'Il risultato è che la comunicazione non trasmette il posizionamento reale: un’azienda storica percepita come anonima, o un piccolo produttore che sembra più improvvisato di quanto sia davvero.',
      ],
      image: '/images/servizi/brand-identity-problema.jpg',
      imageAlt: 'Muro con due tinte accostate senza un criterio, come un brand senza un sistema coerente',
    },
    changeBlock: {
      heading: 'Cosa cambia con un’identità coerente',
      paragraphs: [
        'Chi vi incontra — sul sito, sui social, in fiera, su un’etichetta — riconosce subito che è lo stesso brand, senza doverlo leggere da nessuna parte.',
        'Ogni nuovo materiale — un post, un menù degustazione, una scheda prodotto — si costruisce da solo, perché le regole sono scritte e chiare.',
        'Chi lavorerà con voi in futuro — un grafico, uno stampatore, un nuovo collaboratore — ha un brand book a cui fare riferimento, invece di reinventare tutto da capo.',
      ],
      image: '/images/servizi/brand-identity-cambia.jpg',
      imageAlt: 'Campionario di colori ordinato su un tavolo da lavoro, come un sistema di brand definito',
    },
    includes: [
      { icon: 'target', title: 'Logo e marchio', body: 'Costruzione o revisione del logo, varianti chiaro/scuro/monocromatico, favicon.' },
      { icon: 'palette', title: 'Palette e tipografia', body: 'Colori coerenti con prodotto e territorio, font per titoli e testi con regole d’uso.' },
      { icon: 'compass', title: 'Forme, pattern e motion', body: 'Elementi grafici distintivi — filari, ulivi, colline — riutilizzabili su sito e social.' },
      { icon: 'megaphone', title: 'Messaggio e tono di voce', body: 'Proposta di valore, claim e blocchi di copy di riferimento per chi scrive per voi.' },
      { icon: 'web', title: 'Applicazioni del brand', body: 'Sito, kit social, biglietti da visita, firma email, copertine per menù e presentazioni.' },
      { icon: 'book', title: 'Brand book', body: 'Cosa fare e cosa evitare, specifiche di esportazione, esempi d’uso pronti per chi lavora con voi.' },
    ],
    howWeWork: [
      { n: '1', title: 'Analisi e posizionamento', duration: '1 settimana', body: 'Guardiamo cosa avete già, il settore e come volete essere percepiti.' },
      { n: '2', title: 'Concept e primi mockup', duration: '2 settimane', body: 'Prime direzioni applicate al sito, ai social e alle etichette, non su un foglio bianco.' },
      { n: '3', title: 'Test e definizione del sistema', duration: '1-2 settimane', body: 'Revisione insieme, poi si fissano colori, font e regole d’uso.' },
      { n: '4', title: 'Consegna asset e brand book', duration: '1 settimana', body: 'File pronti per stampa e digitale, più il manuale per chi lavorerà sul brand dopo di noi.' },
    ],
    howWeWorkNote: 'In media: 5-7 settimane dal via alla consegna, a seconda della complessità del sistema.',
    comparisonTable: {
      competitorA: 'Grafico freelance singolo',
      competitorB: 'Agenzia creativa generalista',
      rows: [
        { label: 'Conosce il settore', mg: 'Solo questo', competitorA: 'Dipende', competitorB: 'No' },
        { label: 'Coerenza tra sito, social e stampa', mg: 'Sì, dal primo giorno', competitorA: 'Solo se richiesta', competitorB: 'A volte' },
        { label: 'Brand book operativo incluso', mg: 'Sì', competitorA: 'Raramente', competitorB: 'A volte, a parte' },
        { label: 'Applicato subito su un sito reale', mg: 'Sì', competitorA: 'No', competitorB: 'Raramente' },
        { label: 'Chi vi risponde', mg: 'Chi lavora sul progetto', competitorA: 'Una persona sola', competitorB: 'Un account' },
      ],
      closingLine: 'La differenza non è tecnica. È che quando dite "wine club", "annata" o "DOP" non dobbiamo chiedere cosa significa.',
    },
    investment: {
      eyebrow: 'Prezzi pubblicati',
      heading: 'Quanto costa un’identità coerente',
      subheading: 'Da un refresh mirato al sistema completo, con o senza logo da rifare.',
      plans: [
        {
          ...pricing.brandRefresh,
          offerDescription: 'Il logo resta (o si aggiorna appena), il sistema intorno si mette a posto.',
          benefits: [
            'Palette e tipografia definite',
            'Revisione o piccoli aggiustamenti al logo esistente',
            'Applicazione su sito e kit social',
            'Linee guida essenziali',
          ],
          exclusions: ['Logo costruito da zero', 'Materiali per etichette/packaging', 'Brand book completo'],
          reassurances: ['Prezzi pubblicati: quello che leggete è quello che pagate', 'Tutto resta vostro'],
          closing: 'Utile se il logo funziona ancora ma tutto il resto no.',
        },
        {
          ...pricing.brandIdentityCompleta,
          offerDescription: 'Logo, palette, tono di voce e applicazioni su tutti i touchpoint, con brand book.',
          benefits: [
            'Logo costruito o ridisegnato da zero, con tutte le varianti',
            'Palette, tipografia, forme e pattern distintivi',
            'Messaggio, tono di voce e claim',
            'Applicazioni su sito, social, materiali stampati ed etichette dove serve',
            'Brand book operativo completo',
          ],
          exclusions: ['Stampa fisica dei materiali (fornitori esterni)', 'Fotografia professionale (si valuta a parte)'],
          reassurances: ['Prezzi pubblicati: quello che leggete è quello che pagate', '3 rate senza interessi'],
          closing: 'Cifra precisa dopo una call di 20 minuti, in base a quanti touchpoint servono.',
        },
      ],
      note: 'Cifra precisa dopo una call di 20 minuti: dipende da cosa avete già e da quanti touchpoint servono. Se basta un semplice refresh, non vi proponiamo il pacchetto completo.',
    },
    faqs: [
      { q: 'Ho già un logo a cui sono affezionato, devo per forza rifarlo da zero?', a: 'No. Se il logo funziona, spesso basta un refresh: si definiscono palette, tipografia e regole d’uso intorno a quello che avete già, senza buttarlo via.' },
      { q: 'Ha senso investire in brand identity per un’azienda familiare o piccola?', a: 'Sì, spesso conta più che per un grande gruppo: chi vi conosce di persona si aspetta la stessa cura anche online e sui materiali. È lì che si vede la differenza tra artigianale e trascurato.' },
      { q: 'Il servizio include anche le etichette dei prodotti o solo la comunicazione digitale?', a: 'Dipende dal pacchetto: il sistema — palette, font, elementi grafici — è pensato per funzionare anche su etichette e packaging, ma la produzione grafica delle etichette specifiche si valuta a parte in base al prodotto.' },
      { q: 'Cosa ricevo alla fine, in concreto?', a: 'File del logo in tutte le varianti e formati, palette e font documentati, template per sito e social, e un brand book con le regole d’uso — pronto da passare a chiunque lavori con voi in futuro.' },
      { q: 'Quanto tempo richiede il progetto?', a: 'In media 5-7 settimane dal via alla consegna, a seconda che sia un refresh mirato o un sistema completo da costruire da zero.' },
      { q: 'Questo servizio si può abbinare alla realizzazione del sito o dell’e-commerce?', a: 'Sì, è la combinazione più comune: il brand si applica direttamente al sito o allo store mentre li costruiamo, invece di adattarlo dopo.' },
    ],
    relatedSlugs: ['siti-web-contatti', 'ecommerce-shopify'],
  },
];

export function getServizio(slug) {
  return servizi.find((s) => s.slug === slug);
}
