// Dati geografici per le pagine /geo/[regione] — SEO geo-targeting.
// Fatti geografici e agroalimentari pubblici (regione, capoluogo, vocazione
// produttiva); nessun dato di business o statistica cliente inventata qui.

export const regions = [
  {
    slug: 'piemonte',
    name: 'Piemonte',
    macroArea: 'Nord-Ovest',
    capoluogo: 'Torino',
    cities: ['Alessandria', 'Asti', 'Cuneo', 'Novara', 'Vercelli'],
    lead: 'Terra di grandi vini rossi (Barolo, Barbaresco), nocciole e tartufo bianco d’Alba.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'valle-daosta',
    name: 'Valle d’Aosta',
    macroArea: 'Nord-Ovest',
    capoluogo: 'Aosta',
    cities: ['Saint-Vincent'],
    lead: 'Viticoltura eroica di montagna, piccole produzioni ad alta quota.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'liguria',
    name: 'Liguria',
    macroArea: 'Nord-Ovest',
    capoluogo: 'Genova',
    cities: ['La Spezia', 'Imperia', 'Savona', 'Portovenere'],
    lead: 'Olio extravergine, vigneti a picco sul mare e un turismo enogastronomico fortissimo.',
    caseStudySlug: 'podere-la-vite',
  },
  {
    slug: 'lombardia',
    name: 'Lombardia',
    macroArea: 'Nord-Ovest',
    capoluogo: 'Milano',
    cities: ['Brescia', 'Bergamo', 'Como', 'Cremona', 'Mantova', 'Pavia'],
    lead: 'Franciacorta, Valtellina e una lunga tradizione casearia.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'trentino-alto-adige',
    name: 'Trentino-Alto Adige',
    macroArea: 'Nord-Est',
    capoluogo: 'Trento',
    cities: ['Bolzano', 'Merano', 'Rovereto', 'Riva del Garda'],
    lead: 'Trentodoc, mele di montagna e agriturismi tra le Dolomiti.',
    caseStudySlug: 'podere-la-vite',
  },
  {
    slug: 'veneto',
    name: 'Veneto',
    macroArea: 'Nord-Est',
    capoluogo: 'Venezia',
    cities: ['Verona', 'Padova', 'Vicenza', 'Treviso'],
    lead: 'Prosecco, Amarone della Valpolicella e una filiera vitivinicola tra le più esportate al mondo.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'friuli-venezia-giulia',
    name: 'Friuli-Venezia Giulia',
    macroArea: 'Nord-Est',
    capoluogo: 'Trieste',
    cities: ['Udine', 'Gorizia', 'Aquileia'],
    lead: 'Bianchi di Collio e Colli Orientali tra i più premiati d’Italia.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'emilia-romagna',
    name: 'Emilia-Romagna',
    macroArea: 'Nord-Est',
    capoluogo: 'Bologna',
    cities: ['Parma', 'Reggio Emilia', 'Modena', 'Ferrara', 'Ravenna', 'Rimini'],
    lead: 'Lambrusco, aceto balsamico e una delle filiere agroalimentari più strutturate del Paese.',
    caseStudySlug: 'azienda-rossi',
  },
  {
    slug: 'toscana',
    name: 'Toscana',
    macroArea: 'Centro',
    capoluogo: 'Firenze',
    cities: ['Siena', 'Pisa', 'Arezzo', 'Livorno', 'Grosseto', 'Montalcino'],
    lead: 'Chianti, Brunello di Montalcino, olio extravergine e agriturismi tra i colli.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'umbria',
    name: 'Umbria',
    macroArea: 'Centro',
    capoluogo: 'Perugia',
    cities: ['Terni', 'Assisi', 'Gubbio', 'Orvieto', 'Todi'],
    lead: 'Sagrantino di Montefalco, olio DOP e tartufo, cuore verde dell’Italia agroalimentare.',
    caseStudySlug: 'frantoi-san-lorenzo',
  },
  {
    slug: 'lazio',
    name: 'Lazio',
    macroArea: 'Centro',
    capoluogo: 'Roma',
    cities: ['Frosinone', 'Latina', 'Rieti', 'Viterbo'],
    lead: 'Vini dei Castelli Romani e di Frascati, olio del basso Lazio.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'campania',
    name: 'Campania',
    macroArea: 'Sud',
    capoluogo: 'Napoli',
    cities: ['Salerno', 'Avellino', 'Benevento', 'Caserta'],
    lead: 'Taurasi, Fiano di Avellino, mozzarella di bufala e la costiera come vetrina enoturistica.',
    caseStudySlug: 'podere-la-vite',
  },
  {
    slug: 'basilicata',
    name: 'Basilicata',
    macroArea: 'Sud',
    capoluogo: 'Potenza',
    cities: ['Matera', 'Metaponto'],
    lead: 'Aglianico del Vulture e un territorio agroalimentare ancora poco digitalizzato.',
    caseStudySlug: 'frantoi-san-lorenzo',
  },
  {
    slug: 'molise',
    name: 'Molise',
    macroArea: 'Sud',
    capoluogo: 'Campobasso',
    cities: ['Isernia', 'Termoli'],
    lead: 'Piccole cantine e frantoi a conduzione familiare lungo i tratturi.',
    caseStudySlug: 'tenuta-monteverdi',
  },
  {
    slug: 'sicilia',
    name: 'Sicilia',
    macroArea: 'Isole',
    capoluogo: 'Palermo',
    cities: ['Catania', 'Messina', 'Agrigento', 'Trapani', 'Siracusa', 'Ragusa'],
    lead: 'Vini dell’Etna e di Marsala, olio, agrumi: una delle regioni agroalimentari più vitali d’Italia.',
    caseStudySlug: 'frantoi-san-lorenzo',
  },
  {
    slug: 'sardegna',
    name: 'Sardegna',
    macroArea: 'Isole',
    capoluogo: 'Cagliari',
    cities: ['Sassari', 'Alghero', 'Olbia', 'Nuoro'],
    lead: 'Cannonau, Vermentino e un turismo enogastronomico in forte crescita.',
    caseStudySlug: 'podere-la-vite',
  },
];

export function getRegionBySlug(slug) {
  return regions.find((r) => r.slug === slug) || null;
}
